title: The TDAV Guidebook
email: your-email@example.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/guidebook" # the subpath of your site, e.g. /blog
url: "https://nmutdav.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: your-twitter-handle
github_username: your-github-username

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

excerpt_separator: "\n\n"
markdown: kramdown
