title: The TDAV Guidebook
email: your-email@example.com
description: >-
  Welcome to The TDAV Guidebook, your comprehensive resource for mastering TDAV techniques and tools. Explore detailed guides, practical tips, and expert insights designed to enhance your knowledge and skills. Whether you're a beginner or an experienced user, our site offers valuable content to help you succeed.

baseurl: "/guidebook" # the subpath of your site, e.g. /blog
url: "https://nmutdav.github.io" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: your-twitter-handle
github_username: your-github-username

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

excerpt_separator: "\n\n"
markdown: kramdown
